[project]
name = "pfread"
version = "1.0.0"
description = "LaTeX-aware proofreading toolkit"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"
